version: '3.9'
services:
  backend:
    build:
      context: ./myESIEA-back
    volumes:
      - ./myESIEA-back:/usr/src/app 
      - /usr/src/app/node_modules   
    networks:
      - mynetwork  
    depends_on:
      - mongo

  frontend:
    build:
      context: ./myESIEA-front
    ports:
      - "3000:3000"
    volumes:
      - ./myESIEA-front:/usr/src/app
      - /usr/src/app/node_modules 
    networks:
      - mynetwork

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge